export const PRODUCT_BY_ID_REQUEST = 'PRODUCT_BY_ID_REQUEST';
export const PRODUCT_BY_ID_SUCCSESS = 'PRODUCT_BY_ID_SUCCSESS';
export const PRODUCT_BY_ID_FAILURE = 'PRODUCT_BY_ID_FAILURE';
export const PRODUCT_BY_ID_RESET = 'PRODUCT_BY_ID_RESET';
