export const GET_PRODUCT_LIST_SUCCSESS = 'GET_PRODUCT_LIST_SUCCSESS';
export const GET_PRODUCT_LIST_ERROR = 'GET_PRODUCT_LIST_ERROR';
export const SET_PRODUCT_ORIGINS = 'SET_PRODUCT_ORIGINS';
export const PRODUCT_LIST_RESET = 'GET_PRODUCT_LIST';
export const SET_PRODUCT_LIST_QUERY = 'SET_PRODUCT_LIST_QUERY';
export const RESET_PRODUCT_LIST_QUERIES = 'RESET_PRODUCT_LIST_QUERIES';

export const GET_PRODUCT_BY_ID_SUCCSESS = 'GET_PRODUCT_BY_ID_SUCCSESS';
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR';
export const PRODUCT_PAGE_RESET = 'PRODUCT_PAGE_RESET';

export const CHANGE_PRODUCT_IN_CART = 'CHANGE_PRODUCT_IN_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
