export const PRODUCT_MODAL_TOGGLE = 'PRODUCT_MODAL_TOGGLE';
export const PRODUCT_MODAL_REQUEST = 'PRODUCT_MODAL_REQUEST';
export const PRODUCT_MODAL_SUCCESS = 'PRODUCT_MODAL_SUCCESS';
export const PRODUCT_MODAL_FAILURE = 'PRODUCT_MODAL_FAILURE';
export const PRODUCT_MODAL_CHANGE_PRODUCT = 'PRODUCT_MODAL_CHANGE_PRODUCT';
export const PRODUCT_MODAL_RESET = 'PRODUCT_MODAL_RESET';

export const PRODUCT_FORM_GET_ORIGINS = 'PRODUCT_FORM_GET_ORIGINS';
export const PRODUCT_FORM_GET_ORIGINS_SUCCESS = 'PRODUCT_FORM_GET_ORIGINS_SUCCESS';
export const PRODUCT_FORM_GET_ORIGINS_ERROR = 'PRODUCT_FORM_GET_ORIGINS_SUCCESS';
