export const PRODUCT_MODAL_TOGGLE = 'PRODUCT_MODAL_TOGGLE';
export const PRODUCT_MODAL_REQUEST = 'PRODUCT_MODAL_REQUEST';
export const PRODUCT_MODAL_SUCCESS = 'PRODUCT_MODAL_SUCCESS';
export const PRODUCT_MODAL_FAILURE = 'PRODUCT_MODAL_FAILURE';
export const PRODUCT_MODAL_CHANGE_PRODUCT = 'PRODUCT_MODAL_CHANGE_PRODUCT';
export const PRODUCT_MODAL_RESET = 'PRODUCT_MODAL_RESET';
