export const CART_CHANGE = 'CART_CHANGE';
export const CART_DELETE_PRODUCT = 'CART_DELETE_PRODUCT';
export const CART_TOGGLE_ORDER_MODAL = 'CART_TOGGLE_ORDER_MODAL';
export const CART_SEND_ORDER = 'CART_SEND_ORDER';
export const CART_SENDING_ORDER_SUCCESS = 'CART_SENDING_ORDER_SUCCESS';
export const CART_SENDING_ORDER_FAILURE = 'CART_SENDING_ORDER_FAILURE';
