export const PRODUCT_LIST_SUCCSESS = 'PRODUCT_LIST_SUCCSESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';
export const PRODUCT_LIST_RESET = 'PRODUCT_LIST_RESET';

export const PRODUCT_ORIGINS_REQUEST = 'PRODUCT_ORIGINS_REQUEST';
export const PRODUCT_LIST_QUERIES_SET = 'PRODUCT_LIST_QUERIES_SET';
export const PRODUCT_LIST_QUERIES_RESET = 'PRODUCT_LIST_QUERIES_RESET';
